#!/usr/bin/env python

import subprocess
import random

# ZIZEK

a = ["Office hours, I can't imagine a worse experience than some idiot comes there and starts to ask you questions, which is still tolerable. The problem is that here in the United States students tend to be so open that sooner or later, if you are kind to them, they even start to ask you personal questions about their private problems. What should I tell them? I don't care. Kill yourself, it's not my problem.", "Without the communist oppression, I am absolutely sure I would now be local stupid professor of philosophy in Ljubljana.", "I am a good Hegelian, if you have a good theory, forget about reality.", "I hate students", "I even told students at the New School for example, if you don't give me any of your shitty papers, you get an A. If you give me a paper I may read it and not like it and you can get a lower grade.", "A spectre is haunting Western academia, the spectre of the Cartesian subject.", "As a Marxist, let me add: if anyone tells you Lacan is difficult, this is class propaganda by the enemy.", "Yes, and the age of philosophy in the sense again that we are confronted more and more often with philosophical problems at an everyday level. It is not that you withdraw from daily life into a world of philosophical contemplation. On the contrary, you cannot find your way around daily life itself without answering certain philosophical questions. It is a unique time when everyone is, in a way, forced to be some kind of philosopher.", "Cinema is the ultimate pervert art. It doesn't give you what you desire - it tells you how to desire.", "The true ethical test is not only the readiness to save the victims, but also - even more, perhaps - the ruthless dedication to annihilating those who made them victims.", "As the experience of our post-political liberal-permissive society amply demonstrates, human Rights are ultimately, at their core, simply Rights to violate the Ten Commandments.", "I already am eating from the trash can all the time. The name of this trash can is ideology. The material force of ideology makes me not see what I am effectively eating.", "When authority is backed up by an immediate physical compulsion, what we are dealing with is not authority proper (i.e. symbolic authority), but simply an agency of brute force.", "What if culture itself is nothing but a halt, a break, a respite, in the pursuit of barbarity?", "This proletarianization of the lower salaried bourgeoisie is accompanied by an excess in the opposite direction: the irrationally high pay of top managers and bankers, a level of remuneration that is economically irrational since, as investigations in the US have demonstrated, it tends to be inversely proportional to the company's success.", "Hysteria in capitalism is a rebellion of the subject against being reduced to usefulness."]

subprocess.Popen(["espeak", (random.choice(a))])
